### PR TITLE
Fix issue #20 - author class changed to author-name

### PR DESCRIPTION
**Pull request by cpettifer**

### CODE REVIEW

**Comment by reywood** [comment]
I'm still seeing a class name of "author" in my pull requests. Are there multiple pull request UIs available? Maybe a preview of a new pull request UI?

**Comment by cpettifer** [comment]
That's interesting because someone else in my team at work said they weren't having a problem, so perhaps I have been served some new version, while others are getting the previous / existing version? Maybe hang off for a few days and see what happens on Bitbucket...

**Comment by reywood** [comment]
Maybe you could change the selector to something that would take either class like this:

```javascript
comment.querySelector('.author, .author-name').textContent
```

**Comment by cpettifer** [comment]
That's a good shout - done

**Pull request merged**
